### PR TITLE
ESVonline link reformat

### PR DESCRIPTION
**Pull request by augmentedfourth**
- The "search?q=" part of the URL is no longer necessary, and indeed seems to confuse the site sometimes
- Whenever there was a passage in the list with an ordinal (1Cor, 2John, etc.) it was incorrectly parsed
  - "Romans11:36,1Corinthians10:31" was parsed as "Romans 11:36, Romans 11:1, 1 Corinthians 10:31"
  - I fixed this by replacing the comma with a semicolon in any string matching ',[123][A-Z]'
- These changes are stored in the file 'esvonline_reformat.sh'
  - I ran it as an argument to bash rather than with a hashbang, so it's not executable

### CODE REVIEW

**Comment by augmentedfourth** [comment]
This is evident in the very first link for both the WLC and WSC: https://dailywestminster.wordpress.com/2021/01/01/daily-westminster-jan-1-3/

Also, while I know all of the January links have already been scheduled without this reformat, we should be fine if this doesn't actually go live on the blog until February.

**Comment by RubeRad** [comment]
Nice catch -- this would be necessary also in all the directories for dailyconfession too, right?

**Comment by augmentedfourth** [comment]
No, because dailyconfession still posts with biblegateway links.

Also, I noticed that http://esvonline.org links always redirect to https://www.esv.org, so we could either trust the site to continue redirection or make that change ourselves.

**Comment by RubeRad** [comment]
Hmm, I wonder why I did it that way? 

Well, I'm definitely a 'if it ain't broke don't fix it' kinda guy, let's merge this now to start improving DW in Feb

**Comment by augmentedfourth** [comment]
esvonline.org used to be the place where the online Bible references were stored, but that got changed to esv.org a few years ago. While I get the "if it ain't broke, don't fix it" angle, I also dislike the dependency of relying on someone else's software to continue working as-is in perpetuity.

In any case, this is now pulled in the dailycc clone I use to auto-post these monthly. We might want to look into some sort of CI/CD solution to get changes merged to master automatically deployed to my production machine, but that's a project for another day.

**Pull request merged**
