### PR TITLE
Fix some links for parsing errors with esvonline

### PR DESCRIPTION
**Pull request by augmentedfourth**
In the KJV, 44 & 46 are merely repetitions of v48.

### CODE REVIEW

**Comment by augmentedfourth** [comment]
Still working on this. I'm probably going to squash it all into one commit when I'm done. I'm just checking to fix all links that result in errors on the ESV website; I'm not actually checking whether the passages specifically match all the prooftext references for the standards.

Right now I'm focusing on January through April, and I plan to take a moment every month to check all the links before the script runs to schedule everything.

**Comment by augmentedfourth** [comment]
This is done. I squashed a bunch of individual link fixes into a single commit. They're all pretty simple except for the one on the March 6 (which was originally the sole reason for this PR). The description of that one is the first comment above... In the KJV, 44 & 46 are merely repetitions of v48, and ESV omits 44/46, so I removed them from the reference so the esvonline link will work.

**Comment by augmentedfourth** [comment]
For the link test script, you just provide a month (as prepended to the HTML pages in the repo, e.g. `jun`), and it will output a bare HTML page with all the links for the month. I've clicked through all the links for jan-apr and included all the necessary fixes in this PR.

**Review by RubeRad — APPROVED** [review]
OK now I get what's up with that vv 44/46 -- thanks for this!

**Pull request merged**
