### PR TITLE
fix WSC19 answer wording

### PR DESCRIPTION
**Pull request by augmentedfourth**
https://www.apuritansmind.com/westminster-standards/shorter-catechism/

### CODE REVIEW

**Comment by RubeRad** [comment]
Hmmm, that's debatable. I'm seeing it different ways in various online presentations (more your way though), but the current way is part of the memory structure I key on in https://confessionalouthouse.files.wordpress.com/2010/12/sc24.pdf, parallel with "the pains of death"

**Comment by augmentedfourth** [comment]
Understood. I've been using the iOS app Verses to memorize the WSC and it's pretty clear to me that they pulled it from the apuritansmind.com version. The reformed.org "[Historic Church Documents](https://reformed.org/historic-confessions/1647westminsterconfession/)" section now redirects to the copies hosted at apuritansmind, so I assumed that copy was the same as (or at least related to) your original source.

Merge it or close it at your option. I just created the pull request because this is the wording I've memorized, but different options certainly exist.

**Comment by RubeRad** [comment]
lol I went to opc.org for a tiebreaker, and [they have](https://opc.org/sc.html) "all the miseries in this life"

**Comment by RubeRad** [comment]
I think since Structured Shorter Catechism is also on the daily*.wordpress.com sites, and I used 'all the miseries of this life' on that and don't want to update, I'll leave it as-is.

Thx for continuing to check up on all this and clean it up!

**Pull request closed without merging**
